/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2016-02-18 22:11:37 UTC)
 * on 2016-03-22 at 22:34:36 UTC 
 * Modify at your own risk.
 */

package com.appspot.lthoi_test_harness.playerAPI.model;

/**
 * Model definition for Bet.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the playerAPI. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Bet extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("against_City")
  private java.lang.String againstCity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("against_Team")
  private java.lang.String againstTeam;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer isHouseBet;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("league_Season_ID")
  private java.lang.Integer leagueSeasonID;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double line;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("picked_City")
  private java.lang.String pickedCity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("picked_Team")
  private java.lang.String pickedTeam;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String result;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime start;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("week_Long")
  private java.lang.String weekLong;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("week_Number")
  private java.lang.Integer weekNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("week_Short")
  private java.lang.String weekShort;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAgainstCity() {
    return againstCity;
  }

  /**
   * @param againstCity againstCity or {@code null} for none
   */
  public Bet setAgainstCity(java.lang.String againstCity) {
    this.againstCity = againstCity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAgainstTeam() {
    return againstTeam;
  }

  /**
   * @param againstTeam againstTeam or {@code null} for none
   */
  public Bet setAgainstTeam(java.lang.String againstTeam) {
    this.againstTeam = againstTeam;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public Bet setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Bet setId(java.lang.Integer id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIsHouseBet() {
    return isHouseBet;
  }

  /**
   * @param isHouseBet isHouseBet or {@code null} for none
   */
  public Bet setIsHouseBet(java.lang.Integer isHouseBet) {
    this.isHouseBet = isHouseBet;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLeagueSeasonID() {
    return leagueSeasonID;
  }

  /**
   * @param leagueSeasonID leagueSeasonID or {@code null} for none
   */
  public Bet setLeagueSeasonID(java.lang.Integer leagueSeasonID) {
    this.leagueSeasonID = leagueSeasonID;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLine() {
    return line;
  }

  /**
   * @param line line or {@code null} for none
   */
  public Bet setLine(java.lang.Double line) {
    this.line = line;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPickedCity() {
    return pickedCity;
  }

  /**
   * @param pickedCity pickedCity or {@code null} for none
   */
  public Bet setPickedCity(java.lang.String pickedCity) {
    this.pickedCity = pickedCity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPickedTeam() {
    return pickedTeam;
  }

  /**
   * @param pickedTeam pickedTeam or {@code null} for none
   */
  public Bet setPickedTeam(java.lang.String pickedTeam) {
    this.pickedTeam = pickedTeam;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getResult() {
    return result;
  }

  /**
   * @param result result or {@code null} for none
   */
  public Bet setResult(java.lang.String result) {
    this.result = result;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getStart() {
    return start;
  }

  /**
   * @param start start or {@code null} for none
   */
  public Bet setStart(com.google.api.client.util.DateTime start) {
    this.start = start;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWeekLong() {
    return weekLong;
  }

  /**
   * @param weekLong weekLong or {@code null} for none
   */
  public Bet setWeekLong(java.lang.String weekLong) {
    this.weekLong = weekLong;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getWeekNumber() {
    return weekNumber;
  }

  /**
   * @param weekNumber weekNumber or {@code null} for none
   */
  public Bet setWeekNumber(java.lang.Integer weekNumber) {
    this.weekNumber = weekNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWeekShort() {
    return weekShort;
  }

  /**
   * @param weekShort weekShort or {@code null} for none
   */
  public Bet setWeekShort(java.lang.String weekShort) {
    this.weekShort = weekShort;
    return this;
  }

  @Override
  public Bet set(String fieldName, Object value) {
    return (Bet) super.set(fieldName, value);
  }

  @Override
  public Bet clone() {
    return (Bet) super.clone();
  }

}
