/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2016-02-18 22:11:37 UTC)
 * on 2016-03-22 at 22:34:36 UTC 
 * Modify at your own risk.
 */

package com.appspot.lthoi_test_harness.playerAPI.model;

/**
 * Model definition for Game.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the playerAPI. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Game extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("away_bets")
  private java.util.List<User> awayBets;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("away_city")
  private java.lang.String awayCity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("away_score")
  private java.lang.Integer awayScore;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("away_team")
  private java.lang.String awayTeam;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime freeze;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("home_bets")
  private java.util.List<User> homeBets;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("home_city")
  private java.lang.String homeCity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("home_line")
  private java.lang.Double homeLine;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("home_score")
  private java.lang.Integer homeScore;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("home_team")
  private java.lang.String homeTeam;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("mins_remaining")
  private java.lang.Integer minsRemaining;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("secs_remaining")
  private java.lang.Integer secsRemaining;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime start;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("user_net_home_bet")
  private java.lang.Double userNetHomeBet;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<User> getAwayBets() {
    return awayBets;
  }

  /**
   * @param awayBets awayBets or {@code null} for none
   */
  public Game setAwayBets(java.util.List<User> awayBets) {
    this.awayBets = awayBets;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAwayCity() {
    return awayCity;
  }

  /**
   * @param awayCity awayCity or {@code null} for none
   */
  public Game setAwayCity(java.lang.String awayCity) {
    this.awayCity = awayCity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getAwayScore() {
    return awayScore;
  }

  /**
   * @param awayScore awayScore or {@code null} for none
   */
  public Game setAwayScore(java.lang.Integer awayScore) {
    this.awayScore = awayScore;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAwayTeam() {
    return awayTeam;
  }

  /**
   * @param awayTeam awayTeam or {@code null} for none
   */
  public Game setAwayTeam(java.lang.String awayTeam) {
    this.awayTeam = awayTeam;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getFreeze() {
    return freeze;
  }

  /**
   * @param freeze freeze or {@code null} for none
   */
  public Game setFreeze(com.google.api.client.util.DateTime freeze) {
    this.freeze = freeze;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<User> getHomeBets() {
    return homeBets;
  }

  /**
   * @param homeBets homeBets or {@code null} for none
   */
  public Game setHomeBets(java.util.List<User> homeBets) {
    this.homeBets = homeBets;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getHomeCity() {
    return homeCity;
  }

  /**
   * @param homeCity homeCity or {@code null} for none
   */
  public Game setHomeCity(java.lang.String homeCity) {
    this.homeCity = homeCity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getHomeLine() {
    return homeLine;
  }

  /**
   * @param homeLine homeLine or {@code null} for none
   */
  public Game setHomeLine(java.lang.Double homeLine) {
    this.homeLine = homeLine;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getHomeScore() {
    return homeScore;
  }

  /**
   * @param homeScore homeScore or {@code null} for none
   */
  public Game setHomeScore(java.lang.Integer homeScore) {
    this.homeScore = homeScore;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getHomeTeam() {
    return homeTeam;
  }

  /**
   * @param homeTeam homeTeam or {@code null} for none
   */
  public Game setHomeTeam(java.lang.String homeTeam) {
    this.homeTeam = homeTeam;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Game setId(java.lang.Integer id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMinsRemaining() {
    return minsRemaining;
  }

  /**
   * @param minsRemaining minsRemaining or {@code null} for none
   */
  public Game setMinsRemaining(java.lang.Integer minsRemaining) {
    this.minsRemaining = minsRemaining;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSecsRemaining() {
    return secsRemaining;
  }

  /**
   * @param secsRemaining secsRemaining or {@code null} for none
   */
  public Game setSecsRemaining(java.lang.Integer secsRemaining) {
    this.secsRemaining = secsRemaining;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getStart() {
    return start;
  }

  /**
   * @param start start or {@code null} for none
   */
  public Game setStart(com.google.api.client.util.DateTime start) {
    this.start = start;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getUserNetHomeBet() {
    return userNetHomeBet;
  }

  /**
   * @param userNetHomeBet userNetHomeBet or {@code null} for none
   */
  public Game setUserNetHomeBet(java.lang.Double userNetHomeBet) {
    this.userNetHomeBet = userNetHomeBet;
    return this;
  }

  @Override
  public Game set(String fieldName, Object value) {
    return (Game) super.set(fieldName, value);
  }

  @Override
  public Game clone() {
    return (Game) super.clone();
  }

}
