/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2016-02-18 22:11:37 UTC)
 * on 2016-03-22 at 22:34:36 UTC 
 * Modify at your own risk.
 */

package com.appspot.lthoi_test_harness.playerAPI.model;

/**
 * Model definition for LeagueSeason.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the playerAPI. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class LeagueSeason extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("league_Name")
  private java.lang.String leagueName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("league_Season_ID")
  private java.lang.Integer leagueSeasonID;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer losses;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("num_Players")
  private java.lang.Integer numPlayers;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer position;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer pushes;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer season;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double winnings;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer wins;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLeagueName() {
    return leagueName;
  }

  /**
   * @param leagueName leagueName or {@code null} for none
   */
  public LeagueSeason setLeagueName(java.lang.String leagueName) {
    this.leagueName = leagueName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLeagueSeasonID() {
    return leagueSeasonID;
  }

  /**
   * @param leagueSeasonID leagueSeasonID or {@code null} for none
   */
  public LeagueSeason setLeagueSeasonID(java.lang.Integer leagueSeasonID) {
    this.leagueSeasonID = leagueSeasonID;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLosses() {
    return losses;
  }

  /**
   * @param losses losses or {@code null} for none
   */
  public LeagueSeason setLosses(java.lang.Integer losses) {
    this.losses = losses;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumPlayers() {
    return numPlayers;
  }

  /**
   * @param numPlayers numPlayers or {@code null} for none
   */
  public LeagueSeason setNumPlayers(java.lang.Integer numPlayers) {
    this.numPlayers = numPlayers;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPosition() {
    return position;
  }

  /**
   * @param position position or {@code null} for none
   */
  public LeagueSeason setPosition(java.lang.Integer position) {
    this.position = position;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPushes() {
    return pushes;
  }

  /**
   * @param pushes pushes or {@code null} for none
   */
  public LeagueSeason setPushes(java.lang.Integer pushes) {
    this.pushes = pushes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSeason() {
    return season;
  }

  /**
   * @param season season or {@code null} for none
   */
  public LeagueSeason setSeason(java.lang.Integer season) {
    this.season = season;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getWinnings() {
    return winnings;
  }

  /**
   * @param winnings winnings or {@code null} for none
   */
  public LeagueSeason setWinnings(java.lang.Double winnings) {
    this.winnings = winnings;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getWins() {
    return wins;
  }

  /**
   * @param wins wins or {@code null} for none
   */
  public LeagueSeason setWins(java.lang.Integer wins) {
    this.wins = wins;
    return this;
  }

  @Override
  public LeagueSeason set(String fieldName, Object value) {
    return (LeagueSeason) super.set(fieldName, value);
  }

  @Override
  public LeagueSeason clone() {
    return (LeagueSeason) super.clone();
  }

}
