/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2016-01-08 17:48:37 UTC)
 * on 2016-01-25 at 11:52:24 UTC 
 * Modify at your own risk.
 */

package com.appspot.lthoi_test_harness.playerAPI;

/**
 * Service definition for PlayerAPI (v1).
 *
 * <p>
 * This API includes all of the methods for players. A player need only be authenticated as a user to access it.
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PlayerAPIRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class PlayerAPI extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the playerAPI library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://lthoi-test-harness.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "playerAPI/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public PlayerAPI(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  PlayerAPI(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getMe".
   *
   * This request holds the parameters needed by the playerAPI server.  After setting any optional
   * parameters, call the {@link GetMe#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetMe getMe() throws java.io.IOException {
    GetMe result = new GetMe();
    initialize(result);
    return result;
  }

  public class GetMe extends PlayerAPIRequest<com.appspot.lthoi_test_harness.playerAPI.model.Me> {

    private static final String REST_PATH = "me";

    /**
     * Create a request for the method "getMe".
     *
     * This request holds the parameters needed by the the playerAPI server.  After setting any
     * optional parameters, call the {@link GetMe#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetMe#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetMe() {
      super(PlayerAPI.this, "GET", REST_PATH, null, com.appspot.lthoi_test_harness.playerAPI.model.Me.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetMe setAlt(java.lang.String alt) {
      return (GetMe) super.setAlt(alt);
    }

    @Override
    public GetMe setFields(java.lang.String fields) {
      return (GetMe) super.setFields(fields);
    }

    @Override
    public GetMe setKey(java.lang.String key) {
      return (GetMe) super.setKey(key);
    }

    @Override
    public GetMe setOauthToken(java.lang.String oauthToken) {
      return (GetMe) super.setOauthToken(oauthToken);
    }

    @Override
    public GetMe setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetMe) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetMe setQuotaUser(java.lang.String quotaUser) {
      return (GetMe) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetMe setUserIp(java.lang.String userIp) {
      return (GetMe) super.setUserIp(userIp);
    }

    @Override
    public GetMe set(String parameterName, Object value) {
      return (GetMe) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "setMe".
   *
   * This request holds the parameters needed by the playerAPI server.  After setting any optional
   * parameters, call the {@link SetMe#execute()} method to invoke the remote operation.
   *
   * @param email
   * @param fname
   * @param linitial
   * @param lname
   * @return the request
   */
  public SetMe setMe(java.lang.String email, java.lang.String fname, java.lang.String linitial, java.lang.String lname) throws java.io.IOException {
    SetMe result = new SetMe(email, fname, linitial, lname);
    initialize(result);
    return result;
  }

  public class SetMe extends PlayerAPIRequest<com.appspot.lthoi_test_harness.playerAPI.model.Me> {

    private static final String REST_PATH = "setMe/{email}/{fname}/{linitial}/{lname}";

    /**
     * Create a request for the method "setMe".
     *
     * This request holds the parameters needed by the the playerAPI server.  After setting any
     * optional parameters, call the {@link SetMe#execute()} method to invoke the remote operation.
     * <p> {@link
     * SetMe#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param email
     * @param fname
     * @param linitial
     * @param lname
     * @since 1.13
     */
    protected SetMe(java.lang.String email, java.lang.String fname, java.lang.String linitial, java.lang.String lname) {
      super(PlayerAPI.this, "POST", REST_PATH, null, com.appspot.lthoi_test_harness.playerAPI.model.Me.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      this.fname = com.google.api.client.util.Preconditions.checkNotNull(fname, "Required parameter fname must be specified.");
      this.linitial = com.google.api.client.util.Preconditions.checkNotNull(linitial, "Required parameter linitial must be specified.");
      this.lname = com.google.api.client.util.Preconditions.checkNotNull(lname, "Required parameter lname must be specified.");
    }

    @Override
    public SetMe setAlt(java.lang.String alt) {
      return (SetMe) super.setAlt(alt);
    }

    @Override
    public SetMe setFields(java.lang.String fields) {
      return (SetMe) super.setFields(fields);
    }

    @Override
    public SetMe setKey(java.lang.String key) {
      return (SetMe) super.setKey(key);
    }

    @Override
    public SetMe setOauthToken(java.lang.String oauthToken) {
      return (SetMe) super.setOauthToken(oauthToken);
    }

    @Override
    public SetMe setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SetMe) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SetMe setQuotaUser(java.lang.String quotaUser) {
      return (SetMe) super.setQuotaUser(quotaUser);
    }

    @Override
    public SetMe setUserIp(java.lang.String userIp) {
      return (SetMe) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public SetMe setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String fname;

    /**

     */
    public java.lang.String getFname() {
      return fname;
    }

    public SetMe setFname(java.lang.String fname) {
      this.fname = fname;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String linitial;

    /**

     */
    public java.lang.String getLinitial() {
      return linitial;
    }

    public SetMe setLinitial(java.lang.String linitial) {
      this.linitial = linitial;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String lname;

    /**

     */
    public java.lang.String getLname() {
      return lname;
    }

    public SetMe setLname(java.lang.String lname) {
      this.lname = lname;
      return this;
    }

    @Override
    public SetMe set(String parameterName, Object value) {
      return (SetMe) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link PlayerAPI}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link PlayerAPI}. */
    @Override
    public PlayerAPI build() {
      return new PlayerAPI(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PlayerAPIRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPlayerAPIRequestInitializer(
        PlayerAPIRequestInitializer playerapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(playerapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
